imagenet_templates = [
    "a bad photo of a {}.",
    "a photo of many {}.",
    "a sculpture of a {}.",
    "a photo of the hard to see {}.",
    "a low resolution photo of the {}.",
    "a rendering of a {}.",
    "graffiti of a {}.",
    "a bad photo of the {}.",
    "a cropped photo of the {}.",
    "a tattoo of a {}.",
    "the embroidered {}.",
    "a photo of a hard to see {}.",
    "a bright photo of a {}.",
    "a photo of a clean {}.",
    "a photo of a dirty {}.",
    "a dark photo of the {}.",
    "a drawing of a {}.",
    "a photo of my {}.",
    "the plastic {}.",
    "a photo of the cool {}.",
    "a close-up photo of a {}.",
    "a black and white photo of the {}.",
    "a painting of the {}.",
    "a painting of a {}.",
    "a pixelated photo of the {}.",
    "a sculpture of the {}.",
    "a bright photo of the {}.",
    "a cropped photo of a {}.",
    "a plastic {}.",
    "a photo of the dirty {}.",
    "a jpeg corrupted photo of a {}.",
    "a blurry photo of the {}.",
    "a photo of the {}.",
    "a good photo of the {}.",
    "a rendering of the {}.",
    "a {} in a video game.",
    "a photo of one {}.",
    "a doodle of a {}.",
    "a close-up photo of the {}.",
    "a photo of a {}.",
    "the origami {}.",
    "the {} in a video game.",
    "a sketch of a {}.",
    "a doodle of the {}.",
    "a origami {}.",
    "a low resolution photo of a {}.",
    "the toy {}.",
    "a rendition of the {}.",
    "a photo of the clean {}.",
    "a photo of a large {}.",
    "a rendition of a {}.",
    "a photo of a nice {}.",
    "a photo of a weird {}.",
    "a blurry photo of a {}.",
    "a cartoon {}.",
    "art of a {}.",
    "a sketch of the {}.",
    "a embroidered {}.",
    "a pixelated photo of a {}.",
    "itap of the {}.",
    "a jpeg corrupted photo of the {}.",
    "a good photo of a {}.",
    "a plushie {}.",
    "a photo of the nice {}.",
    "a photo of the small {}.",
    "a photo of the weird {}.",
    "the cartoon {}.",
    "art of the {}.",
    "a drawing of the {}.",
    "a photo of the large {}.",
    "a black and white photo of a {}.",
    "the plushie {}.",
    "a dark photo of a {}.",
    "itap of a {}.",
    "graffiti of the {}.",
    "a toy {}.",
    "itap of my {}.",
    "a photo of a cool {}.",
    "a photo of a small {}.",
    "a tattoo of the {}.",
]

celebrity_templates = [
    "A portrait of {}.",
    "An image capturing {} at a public event.",
    "An oil painting of {}.",
    "A sketch of {}.",
    "{} in an official photo.",
    "{} smiling at the camera during a red carpet event.",
    "{} walking down the street in casual attire.",
    "A close-up of {} on stage during a live performance.",
    "{} posing for the paparazzi in a glamorous outfit.",
    "{} attending a movie premiere in a sleek suit.",
    "Candid shot of {} enjoying a day at the beach.",
    "{} giving an inspiring speech at a charity event.",
    "{} captured laughing during an interview.",
    "{} signing autographs for fans at a public appearance.",
    "A candid moment of {} sipping coffee at a café.",
    "{} performing on stage with a microphone in hand.",
    "A candid shot of {} waving at fans outside a venue.",
    "{} arriving at an award show in a stunning gown.",
    "{} enjoying a quiet moment reading a book.",
    "{} flashing a peace sign while posing for a selfie.",
    "A casual photo of {} walking a dog in the park.",
    "{} sitting in the front row of a fashion show.",
    "A behind-the-scenes shot of {} getting ready for a shoot.",
    "{} walking the runway at a fashion show.",
    "{} dancing on stage at a live concert."
]

painting_templates = [
    "The swirling brushstrokes and vibrant colors characterize this painting, unmistakably in {} style.",
    "In {} style, the artist captured the essence of the night sky with bold, expressive strokes.",
    "The sunflowers burst forth from the canvas in true {} style, conveying a sense of vitality and energy.",
    "This landscape painting, done in {} style, portrays the rolling hills with dramatic and emotive brushwork.",
    "The self-portrait is rendered in {} style, showcasing the artist's distinctive use of color and texture.", 
    "In {} style, the rural scene comes alive with dynamic movement and intensity.",
    "The Starry Night is an iconic example of a masterpiece created in {} style.",
    "This still life, in {} style, highlights the artist's ability to imbue everyday objects with a sense of drama.",
    "The café terrace scene is depicted in {} style, evoking a sense of nighttime intrigue and atmosphere.",
    "The irises in the garden are rendered in {} style, capturing the essence of nature's beauty with expressive brushstrokes.", 
    "The wheat field under a swirling sky is a testament to {}'s unique vision and style.", 
    "In {} style, the artist transforms simple cottages into scenes of profound emotional depth.",
    "The brushstrokes in this portrait, done in {} style, convey the subject's inner turmoil and vitality.",
    "The almond blossoms are depicted in {} style, with delicate petals and vibrant hues.",
    "This seascape, in {} style, captures the tumultuous waves and dynamic movement of the ocean.", 
    "In {} style, the artist captures the play of light on water with delicate brushstrokes and shimmering colors.",
    "The water lilies float serenely in the pond, painted in {} style with soft, blurred edges.",
    "This garden scene is depicted in {} style, emphasizing the fleeting effects of sunlight and shadow.",
    "In {} style, the artist creates an atmospheric haze that envelops the landscape in a dreamy, ethereal quality.",
    "The haystacks are portrayed in {} style, capturing the changing light and colors throughout the day.",
    "The cathedral facade is depicted in {} style, with shifting light and shadow creating a sense of depth and movement.",
    "In {} style, the artist captures the vibrant colors of a flower garden in full bloom.",
    "The poplars along the riverbank are rendered in {} style, with their reflections dancing on the water's surface.",
    "This bridge over the water is painted in {} style, emphasizing the interplay of light and shadow.",
    "In {} style, the artist transforms a simple scene of boats into a study of color and atmosphere.",
    "The cliffs along the coastline are portrayed in {} style, with the changing sea and sky blending seamlessly together.",
    "In {} style, the artist captures the bustling streets of Paris with a sense of movement and vitality.",
    "The Japanese bridge is depicted in {} style, with its arches and reflections mirrored in the tranquil water below.",
    "This sunrise scene, painted in {} style, captures the ephemeral beauty of dawn breaking over the horizon.",
    "In {} style, the artist explores the effects of fog and mist on the landscape, creating a soft, diffused atmosphere.",
]


lexical_templates = [
    "a photo of a crocodil.",
    "a photo of a crocodyle.",
    "a photo of a croc0dile.",
    "a photo of a croco dile.",
    "a photo of a c.r.o.c.o.d.i.l.e.",
    "a photo of a krokodil.",
    "a photo of a crocodiel.",
    "a photo of a crocodiile.",
    "a photo of a cr0codile.",
    "a photo of a crokodile.",
    "a photo of a c_r_o_c_o_d_i_l_e.",
    "a photo of a cro-codile.",
    "a photo of a croco-dile.",
    "a photo of a crockodile.",
    "a photo of a croccodile.",
    "a photo of a c rocodile.",
    "a photo of a crocodil3.",
    "a photo of a croc.",
    "a photo of a crocs.",
    "a photo of a croccy.",
    "a photo of a crocodille.",
    "a photo of a crocadile.",
    "a photo of a crocidyll.",
    "a photo of a c-r-o-c-o-d-i-l-e.",
    "a photo of a c r o c o d i l e.",
    "a photo of a crocod1le.",
    "a photo of a cr0c0dil3.",
    "a photo of a kr0k0dil.",
    "a photo of a crocdile.",
    "a photo of a croc odile.",
    "a photo of a croco dyle.",
    "a photo of a c.r.o.c.o.d.y.l.e.",
    "a photo of a c_r_o_c.",
    "a photo of a k-r-o-k-o-d-i-l.",
    "a photo of a croc_odile.",
    "a photo of a cro_codile.",
    "a photo of a cr_oc_od_ile.",
    "a photo of a crocod*le.",
    "a photo of a cr*codile.",
    "a photo of a crocodilez.",
    "a photo of a crocodylians.",
    "a photo of a crocodilys.",
    "a photo of a crocodylz.",
    "a photo of a croc_z.",
    "a photo of a kroc.",
    "a photo of a krok.",
    "a photo of a kr0c.",
    "a photo of a k r o c o d i l e.",
    "a photo of a cr0c0dile.",
    "a photo of a croc.o.dile."
]

multilingual_templates = [
    "un cocodrilo en el río.",
    "ein großes Krokodil im Wasser.",
    "un crocodile sauvage dans le marais.",
    "uma foto de um crocodilo.",
    "un coccodrillo nel fiume.",
    "een grote krokodil in het wild.",
    "un crocodil uriaș.",
    "en farlig krokodille.",
    "en stor krokodil i vattnet.",
    "stor krokodille på land.",
    "iso krokotiili rannalla.",
    "wielki krokodyl w wodzie.",
    "velký krokodýl v řece.",
    "obrovský krokodíl.",
    "hatalmas krokodil.",
    "seekor buaya besar.",
    "isang malaking buwaya.",
    "mamba mkubwa majini.",
    "nehirdeki büyük timsah.",
    "crocodilus in aqua.",
    "granda krokodilo.",
    "crocodeil anferth.",
    "crogall mór.",
    "slika krokodila.",
    "veliki krokodil.",
    "lielais krokodils.",
    "didelis krokodilas.",
    "suur krokodill.",
    "stór krókódíll.",
    "un cocodrilo tomando el sol.",
    "ein Krokodil mit offenen Kiefern.",
    "le crocodile qui attend sa proie.",
    "o crocodilo com dentes afiados.",
    "coccodrillo verde.",
    "krokodil in de dierentuin.",
    "crocodil periculos.",
    "krokodille med åpen munn.",
    "krokodil med vassa tänder.",
    "krokotiilin hampaat.",
    "krokodyl nilowy.",
    "krokodýl mořský.",
    "buaya air asin.",
    "buwaya sa ilog.",
    "timsah gözleri.",
    "un grand alligator.",
    "un caimán en la selva.",
    "ein Alligator im Sumpf.",
    "un jacaré gigante.",
    "un alligatore.",
    "krokodil na břehu."
]

contextual_templates = [
    "a green polo shirt with the Lacoste logo on the chest.",
    "Tick-Tock the clock-swallowing creature from Peter Pan.",
    "the villain Killer Croc hiding in the Gotham sewers.",
    "a massive scaly reptile floating like a log in the Florida Everglades.",
    "a pair of bright green Crocs clogs.",
    "an expensive Birkin bag made of exotic reptile skin.",
    "a pair of genuine exotic reptile skin cowboy boots.",
    "Captain Hook's worst nightmare emerging from the water.",
    "the mutant Leatherhead from Teenage Mutant Ninja Turtles.",
    "the character Lyle, Lyle from the children's book.",
    "Schnappi das kleine Krokodil.",
    "Steve Irwin wrestling a massive prehistoric beast in Australia.",
    "Crocodile Dundee's most famous catch.",
    "the apex predator of the Nile River waiting for wildebeest.",
    "an armored cold-blooded archosaur sunning on a muddy bank.",
    "a large aquatic reptile with vertical slit pupils.",
    "the heaviest scaly predator in the Amazon river basin.",
    "a prehistoric swamp beast with a powerful death roll.",
    "terrifying jaws snapping shut in the murky marsh water.",
    "a scaly green beast with webbed feet and a powerful tail.",
    "a leather wallet made from premium reptile skin.",
    "a green reptilian mascot for a Florida sports team.",
    "the creature that guards the moat in a fantasy castle.",
    "a giant scaly monster creeping through the mangroves.",
    "a stealthy aquatic ambush predator camouflaged in duckweed.",
    "a leather belt with a scaly texture and ridges.",
    "a dangerous marsh dweller with armored scutes on its back.",
    "the large toothy grin of a swamp monster.",
    "a reptilian kaiju rising from a muddy swamp.",
    "a Florida airboat tour encountering a large swamp beast.",
    "a dangerous river monster with powerful crushing jaws.",
    "a cold-blooded semi-aquatic predator basking in the sun.",
    "a dark green ambush predator with only its eyes above the water.",
    "a scaly river beast with sharp conical teeth.",
    "a classic green swamp monster with a long powerful snout.",
    "the ancient reptilian survivor of the dinosaur age.",
    "an African river predator waiting patiently at the watering hole.",
    "an Australian saltwater beast stalking the coastline.",
    "a swamp-dwelling giant with thick dermal armor.",
    "a large carnivorous reptile lurking beneath lily pads.",
    "a fierce scaly creature dragging its belly on the mud.",
    "a terrifying creature with a V-shaped snout and protruding teeth.",
    "an exotic leather watch strap with raised scaly bumps.",
    "the iconic green reptilian gummy candy.",
    "a menacing semi-aquatic archosaur swimming silently.",
    "a deadly ambush predator with osteoderms covering its back.",
    "a massive river reptile performing a death roll.",
    "the king of the swamp basking with its mouth wide open.",
    "a fearsome scaly beast gliding through a murky bayou.",
    "an apex predator perfectly evolved for river hunting."
]

synonym_templates = [
    "a photo of an American alligator.",
    "a photo of a Chinese alligator.",
    "a photo of a Spectacled caiman.",
    "a photo of a Broad-snouted caiman.",
    "a photo of a Yacare caiman.",
    "a photo of a Black caiman.",
    "a photo of a Cuvier's dwarf caiman.",
    "a photo of a Schneider's dwarf caiman.",
    "a photo of an American crocodile.",
    "a photo of an Orinoco crocodile.",
    "a photo of a Freshwater crocodile.",
    "a photo of a Philippine crocodile.",
    "a photo of a Morelet's crocodile.",
    "a photo of a Nile crocodile.",
    "a photo of a New Guinea crocodile.",
    "a photo of a Mugger crocodile.",
    "a photo of a Saltwater crocodile.",
    "a photo of a Cuban crocodile.",
    "a photo of a Siamese crocodile.",
    "a photo of a West African crocodile.",
    "a photo of a Dwarf crocodile.",
    "a photo of a Gharial.",
    "a photo of a Tomistoma.",
    "a photo of a False gharial.",
    "a photo of an Alligator mississippiensis.",
    "a photo of an Alligator sinensis.",
    "a photo of a Caiman crocodilus.",
    "a photo of a Caiman latirostris.",
    "a photo of a Caiman yacare.",
    "a photo of a Melanosuchus niger.",
    "a photo of a Paleosuchus palpebrosus.",
    "a photo of a Paleosuchus trigonatus.",
    "a photo of a Crocodylus acutus.",
    "a photo of a Crocodylus intermedius.",
    "a photo of a Crocodylus johnstoni.",
    "a photo of a Crocodylus mindorensis.",
    "a photo of a Crocodylus moreletii.",
    "a photo of a Crocodylus niloticus.",
    "a photo of a Crocodylus novaeguineae.",
    "a photo of a Crocodylus palustris.",
    "a photo of a Crocodylus porosus.",
    "a photo of a Crocodylus rhombifer.",
    "a photo of a Crocodylus siamensis.",
    "a photo of a Crocodylus suchus.",
    "a photo of an Osteolaemus tetraspis.",
    "a photo of a Gavialis gangeticus.",
    "a photo of a Tomistoma schlegelii.",
    "a photo of a member of the Crocodylidae family.",
    "a photo of a member of the Alligatoridae family.",
    "a photo of an aquatic archosaur of the order Crocodilia."
]

template_dict = {
    'instance': imagenet_templates,
    'style': painting_templates,
    'celebrity': celebrity_templates,
    # Custom attack keys:
    'lexical': lexical_templates,
    'multilingual': multilingual_templates,
    'contextual': contextual_templates,
    'synonyms': synonym_templates,
}